apiVersion: apps/v1
kind: Deployment
metadata:
  name: fr-frontend
  labels:
    app: fr-frontend
spec:
  selector:
    matchLabels:
      app: fr-frontend
  replicas: 2
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate: 
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: fr-frontend
    spec:
      containers:
        - image: virtual8/face-recognition-frontend
          imagePullPolicy: Always
          name: fr-frontend
          ports:
            - containerPort: 80
