apiVersion: apps/v1
kind: Deployment
metadata:
  name: fr-webapp
  labels:
    app: fr-webapp
spec:
  selector:
    matchLabels:
      app: fr-webapp
  replicas: 1
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate: 
      maxUnavailable: 2
      maxSurge: 1
  template:
    metadata:
      labels:
        app: fr-webapp
    spec:
      containers:
      - image: virtual8/face-recognition-webapp:latest
        imagePullPolicy: Always
        name: fr-webapp
        env:
          - name: FR_LOGIC_API_URL
            value: "http://fr-logic"
          - name: FR_STORE_URL
            value: "http://fr-storage"
          - name: SPRING_DS_URL
            value: "jdbc:mysql://mysql/devdb"
          - name: SPRING_DDL
            value: "create" 
          - name: spring.datasource.username
            value: "dbuser"
          - name: spring.datasource.password
            value: "dbpassword"
        ports:
          - containerPort: 8080
